// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: courseoccasions.sql

package database

import (
	"context"
)

const deleteCourseOccasion = `-- name: DeleteCourseOccasion :exec
DELETE FROM course_occasions
WHERE
    id = ?
`

func (q *Queries) DeleteCourseOccasion(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCourseOccasion, id)
	return err
}

const getCourseOccasionByID = `-- name: GetCourseOccasionByID :one
SELECT
    id, course_id, date, name
FROM
    course_occasions
WHERE
    id = ?
`

func (q *Queries) GetCourseOccasionByID(ctx context.Context, id int64) (CourseOccasion, error) {
	row := q.db.QueryRowContext(ctx, getCourseOccasionByID, id)
	var i CourseOccasion
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Date,
		&i.Name,
	)
	return i, err
}

const getCourseOccasions = `-- name: GetCourseOccasions :many
SELECT
    id, course_id, date, name
FROM
    course_occasions
WHERE
    course_id = ?
`

func (q *Queries) GetCourseOccasions(ctx context.Context, courseID int64) ([]CourseOccasion, error) {
	rows, err := q.db.QueryContext(ctx, getCourseOccasions, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CourseOccasion
	for rows.Next() {
		var i CourseOccasion
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Date,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveCourseOccasion = `-- name: SaveCourseOccasion :one
INSERT INTO
    course_occasions (course_id, date, name)
VALUES
    (?, ?, ?) RETURNING id, course_id, date, name
`

type SaveCourseOccasionParams struct {
	CourseID int64
	Date     string
	Name     string
}

func (q *Queries) SaveCourseOccasion(ctx context.Context, arg SaveCourseOccasionParams) (CourseOccasion, error) {
	row := q.db.QueryRowContext(ctx, saveCourseOccasion, arg.CourseID, arg.Date, arg.Name)
	var i CourseOccasion
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Date,
		&i.Name,
	)
	return i, err
}

const updateCourseOccasion = `-- name: UpdateCourseOccasion :exec
UPDATE course_occasions
SET
    name = ?
WHERE
    id = ?
`

type UpdateCourseOccasionParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateCourseOccasion(ctx context.Context, arg UpdateCourseOccasionParams) error {
	_, err := q.db.ExecContext(ctx, updateCourseOccasion, arg.Name, arg.ID)
	return err
}
