// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: lessons.sql

package database

import (
	"context"
	"database/sql"
)

const deleteAllLessonDates = `-- name: DeleteAllLessonDates :exec
DELETE FROM lesson_dates
WHERE
  lesson_id = ?
`

func (q *Queries) DeleteAllLessonDates(ctx context.Context, lessonID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAllLessonDates, lessonID)
	return err
}

const deleteLesson = `-- name: DeleteLesson :exec
DELETE FROM lessons
WHERE
  id = ?
`

func (q *Queries) DeleteLesson(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLesson, id)
	return err
}

const deleteLessonDate = `-- name: DeleteLessonDate :exec
DELETE FROM lesson_dates
WHERE
  lesson_id = ?
  AND date_id = ?
`

type DeleteLessonDateParams struct {
	LessonID int64
	DateID   int64
}

func (q *Queries) DeleteLessonDate(ctx context.Context, arg DeleteLessonDateParams) error {
	_, err := q.db.ExecContext(ctx, deleteLessonDate, arg.LessonID, arg.DateID)
	return err
}

const deleteLessonStandard = `-- name: DeleteLessonStandard :exec
DELETE FROM lesson_standards
WHERE
  std_id = ?
  AND lesson_id = ?
`

type DeleteLessonStandardParams struct {
	StdID    int64
	LessonID int64
}

func (q *Queries) DeleteLessonStandard(ctx context.Context, arg DeleteLessonStandardParams) error {
	_, err := q.db.ExecContext(ctx, deleteLessonStandard, arg.StdID, arg.LessonID)
	return err
}

const getLesson = `-- name: GetLesson :one
SELECT
  l.id, l.unit_id, l.number, l.name, l.description,
  u.number AS unit_num,
  u.name AS unit_name
FROM
  lessons l
  JOIN units u ON l.unit_id = u.id
WHERE
  l.id = ?
`

type GetLessonRow struct {
	ID          int64
	UnitID      int64
	Number      int64
	Name        sql.NullString
	Description sql.NullString
	UnitNum     int64
	UnitName    string
}

func (q *Queries) GetLesson(ctx context.Context, id int64) (GetLessonRow, error) {
	row := q.db.QueryRowContext(ctx, getLesson, id)
	var i GetLessonRow
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.UnitNum,
		&i.UnitName,
	)
	return i, err
}

const getLessonDates = `-- name: GetLessonDates :many
SELECT
  d.date
FROM
  lesson_dates ld
  JOIN dates d ON d.id = ld.date_id
WHERE
  lesson_id = ?
`

func (q *Queries) GetLessonDates(ctx context.Context, lessonID int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getLessonDates, lessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var date string
		if err := rows.Scan(&date); err != nil {
			return nil, err
		}
		items = append(items, date)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessons = `-- name: GetLessons :many
SELECT
  l.id,
  l.number,
  l.name,
  l.description,
  u.number AS unit_num,
  u.name AS unit_name
FROM
  lessons l
  JOIN units u ON l.unit_id = u.id
WHERE
  l.unit_id = ?
`

type GetLessonsRow struct {
	ID          int64
	Number      int64
	Name        sql.NullString
	Description sql.NullString
	UnitNum     int64
	UnitName    string
}

func (q *Queries) GetLessons(ctx context.Context, unitID int64) ([]GetLessonsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLessons, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLessonsRow
	for rows.Next() {
		var i GetLessonsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Name,
			&i.Description,
			&i.UnitNum,
			&i.UnitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessonsOnDate = `-- name: GetLessonsOnDate :many
SELECT
  ld.lesson_id, ld.date_id,
  l.id, l.unit_id, l.number, l.name, l.description
from
  lesson_dates ld
  JOIN dates d ON d.id = ld.date_id
  JOIN lessons l ON l.id = ld.lesson_id
WHERE
  d.date = ?
  and d.term_id = ?
`

type GetLessonsOnDateParams struct {
	Date   string
	TermID int64
}

type GetLessonsOnDateRow struct {
	LessonID    int64
	DateID      int64
	ID          int64
	UnitID      int64
	Number      int64
	Name        sql.NullString
	Description sql.NullString
}

func (q *Queries) GetLessonsOnDate(ctx context.Context, arg GetLessonsOnDateParams) ([]GetLessonsOnDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getLessonsOnDate, arg.Date, arg.TermID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLessonsOnDateRow
	for rows.Next() {
		var i GetLessonsOnDateRow
		if err := rows.Scan(
			&i.LessonID,
			&i.DateID,
			&i.ID,
			&i.UnitID,
			&i.Number,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessonsOnDateForCourse = `-- name: GetLessonsOnDateForCourse :many
SELECT
  ld.lesson_id, ld.date_id,
  l.id, l.unit_id, l.number, l.name, l.description,
  u.number as unit_num,
  u.name as unit_name
from
  lesson_dates ld
  JOIN dates d ON d.id = ld.date_id
  JOIN lessons l ON l.id = ld.lesson_id
  JOIN units u ON u.id = l.unit_id
  JOIN courses c ON c.id = u.course_id
  JOIN terms t ON t.id = c.term_id
WHERE
  d.date = ?
  and c.id = ?
`

type GetLessonsOnDateForCourseParams struct {
	Date string
	ID   int64
}

type GetLessonsOnDateForCourseRow struct {
	LessonID    int64
	DateID      int64
	ID          int64
	UnitID      int64
	Number      int64
	Name        sql.NullString
	Description sql.NullString
	UnitNum     int64
	UnitName    string
}

func (q *Queries) GetLessonsOnDateForCourse(ctx context.Context, arg GetLessonsOnDateForCourseParams) ([]GetLessonsOnDateForCourseRow, error) {
	rows, err := q.db.QueryContext(ctx, getLessonsOnDateForCourse, arg.Date, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLessonsOnDateForCourseRow
	for rows.Next() {
		var i GetLessonsOnDateForCourseRow
		if err := rows.Scan(
			&i.LessonID,
			&i.DateID,
			&i.ID,
			&i.UnitID,
			&i.Number,
			&i.Name,
			&i.Description,
			&i.UnitNum,
			&i.UnitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveLesson = `-- name: SaveLesson :one
INSERT INTO
  lessons (number, name, description, unit_id)
VALUES
  (?, ?, ?, ?) RETURNING id, unit_id, number, name, description
`

type SaveLessonParams struct {
	Number      int64
	Name        sql.NullString
	Description sql.NullString
	UnitID      int64
}

func (q *Queries) SaveLesson(ctx context.Context, arg SaveLessonParams) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, saveLesson,
		arg.Number,
		arg.Name,
		arg.Description,
		arg.UnitID,
	)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.Number,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const saveLessonDate = `-- name: SaveLessonDate :one
INSERT INTO
  lesson_dates (lesson_id, date_id)
VALUES
  (?, ?) RETURNING lesson_id, date_id
`

type SaveLessonDateParams struct {
	LessonID int64
	DateID   int64
}

func (q *Queries) SaveLessonDate(ctx context.Context, arg SaveLessonDateParams) (LessonDate, error) {
	row := q.db.QueryRowContext(ctx, saveLessonDate, arg.LessonID, arg.DateID)
	var i LessonDate
	err := row.Scan(&i.LessonID, &i.DateID)
	return i, err
}

const saveLessonStandard = `-- name: SaveLessonStandard :exec
INSERT INTO
  lesson_standards (std_id, lesson_id)
VALUES
  (?, ?)
`

type SaveLessonStandardParams struct {
	StdID    int64
	LessonID int64
}

func (q *Queries) SaveLessonStandard(ctx context.Context, arg SaveLessonStandardParams) error {
	_, err := q.db.ExecContext(ctx, saveLessonStandard, arg.StdID, arg.LessonID)
	return err
}

const updateLesson = `-- name: UpdateLesson :exec
UPDATE lessons
set
  name = ?,
  number = ?,
  description = ?
WHERE
  id = ?
`

type UpdateLessonParams struct {
	Name        sql.NullString
	Number      int64
	Description sql.NullString
	ID          int64
}

func (q *Queries) UpdateLesson(ctx context.Context, arg UpdateLessonParams) error {
	_, err := q.db.ExecContext(ctx, updateLesson,
		arg.Name,
		arg.Number,
		arg.Description,
		arg.ID,
	)
	return err
}
