// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: standards.sql

package database

import (
	"context"
	"database/sql"
)

const getAllObjectives = `-- name: GetAllObjectives :many
SELECT id, number, name, description, set_id, parent_id FROM standards WHERE set_id = ? AND parent_id IS NOT NULL
`

func (q *Queries) GetAllObjectives(ctx context.Context, setID int64) ([]Standard, error) {
	rows, err := q.db.QueryContext(ctx, getAllObjectives, setID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Standard
	for rows.Next() {
		var i Standard
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Name,
			&i.Description,
			&i.SetID,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCourseStandards = `-- name: GetCourseStandards :many
SELECT id, number, name, description, set_id, parent_id FROM standards WHERE set_id = ? AND parent_id IS NULL
`

func (q *Queries) GetCourseStandards(ctx context.Context, setID int64) ([]Standard, error) {
	rows, err := q.db.QueryContext(ctx, getCourseStandards, setID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Standard
	for rows.Next() {
		var i Standard
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Name,
			&i.Description,
			&i.SetID,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLessonStandards = `-- name: GetLessonStandards :many
SELECT o.id, o.number, o.name, o.description, o.set_id, o.parent_id, s.number as parent_num FROM standards o
JOIN standards s ON s.id = o.parent_id 
JOIN lesson_standards ls 
ON ls.std_id = o.id AND ls.lesson_id = ?
`

type GetLessonStandardsRow struct {
	ID          int64
	Number      int64
	Name        string
	Description sql.NullString
	SetID       int64
	ParentID    sql.NullInt64
	ParentNum   int64
}

func (q *Queries) GetLessonStandards(ctx context.Context, lessonID int64) ([]GetLessonStandardsRow, error) {
	rows, err := q.db.QueryContext(ctx, getLessonStandards, lessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLessonStandardsRow
	for rows.Next() {
		var i GetLessonStandardsRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Name,
			&i.Description,
			&i.SetID,
			&i.ParentID,
			&i.ParentNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStandardByID = `-- name: GetStandardByID :one
SELECT o.id, o.number, o.name, o.description, o.set_id, o.parent_id, s.number as parent_num FROM standards o
JOIN standards s ON s.id = o.parent_id
WHERE o.id = ?
`

type GetStandardByIDRow struct {
	ID          int64
	Number      int64
	Name        string
	Description sql.NullString
	SetID       int64
	ParentID    sql.NullInt64
	ParentNum   int64
}

func (q *Queries) GetStandardByID(ctx context.Context, id int64) (GetStandardByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getStandardByID, id)
	var i GetStandardByIDRow
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.SetID,
		&i.ParentID,
		&i.ParentNum,
	)
	return i, err
}

const getStandardObjectives = `-- name: GetStandardObjectives :many
SELECT o.id, o.number, o.name, o.description, o.set_id, o.parent_id, s.number as parent_num
FROM standards o
JOIN standards s ON s.id = o.parent_id 
WHERE o.parent_id = ?
`

type GetStandardObjectivesRow struct {
	ID          int64
	Number      int64
	Name        string
	Description sql.NullString
	SetID       int64
	ParentID    sql.NullInt64
	ParentNum   int64
}

func (q *Queries) GetStandardObjectives(ctx context.Context, parentID sql.NullInt64) ([]GetStandardObjectivesRow, error) {
	rows, err := q.db.QueryContext(ctx, getStandardObjectives, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStandardObjectivesRow
	for rows.Next() {
		var i GetStandardObjectivesRow
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Name,
			&i.Description,
			&i.SetID,
			&i.ParentID,
			&i.ParentNum,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveStandard = `-- name: SaveStandard :one
INSERT INTO standards (
  parent_id, set_id, number, name, description
) VALUES (
  ?, ?, ?, ?, ?
)
RETURNING id, number, name, description, set_id, parent_id
`

type SaveStandardParams struct {
	ParentID    sql.NullInt64
	SetID       int64
	Number      int64
	Name        string
	Description sql.NullString
}

func (q *Queries) SaveStandard(ctx context.Context, arg SaveStandardParams) (Standard, error) {
	row := q.db.QueryRowContext(ctx, saveStandard,
		arg.ParentID,
		arg.SetID,
		arg.Number,
		arg.Name,
		arg.Description,
	)
	var i Standard
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Name,
		&i.Description,
		&i.SetID,
		&i.ParentID,
	)
	return i, err
}
