// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: termoccasions.sql

package database

import (
	"context"
)

const deleteTermOccasion = `-- name: DeleteTermOccasion :exec
DELETE FROM term_occasions
WHERE
    id = ?
`

func (q *Queries) DeleteTermOccasion(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTermOccasion, id)
	return err
}

const getTermOccasionByID = `-- name: GetTermOccasionByID :one
SELECT
    id, term_id, date, name
FROM
    term_occasions
WHERE
    id = ?
`

func (q *Queries) GetTermOccasionByID(ctx context.Context, id int64) (TermOccasion, error) {
	row := q.db.QueryRowContext(ctx, getTermOccasionByID, id)
	var i TermOccasion
	err := row.Scan(
		&i.ID,
		&i.TermID,
		&i.Date,
		&i.Name,
	)
	return i, err
}

const getTermOccasions = `-- name: GetTermOccasions :many
SELECT
    id, term_id, date, name
FROM
    term_occasions
WHERE
    term_id = ?
`

func (q *Queries) GetTermOccasions(ctx context.Context, termID int64) ([]TermOccasion, error) {
	rows, err := q.db.QueryContext(ctx, getTermOccasions, termID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TermOccasion
	for rows.Next() {
		var i TermOccasion
		if err := rows.Scan(
			&i.ID,
			&i.TermID,
			&i.Date,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveTermOccasion = `-- name: SaveTermOccasion :one
INSERT INTO
    term_occasions (term_id, date, name)
VALUES
    (?, ?, ?) RETURNING id, term_id, date, name
`

type SaveTermOccasionParams struct {
	TermID int64
	Date   string
	Name   string
}

func (q *Queries) SaveTermOccasion(ctx context.Context, arg SaveTermOccasionParams) (TermOccasion, error) {
	row := q.db.QueryRowContext(ctx, saveTermOccasion, arg.TermID, arg.Date, arg.Name)
	var i TermOccasion
	err := row.Scan(
		&i.ID,
		&i.TermID,
		&i.Date,
		&i.Name,
	)
	return i, err
}

const updateTermOccasion = `-- name: UpdateTermOccasion :exec
UPDATE term_occasions
SET
    name = ?
WHERE
    id = ?
`

type UpdateTermOccasionParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateTermOccasion(ctx context.Context, arg UpdateTermOccasionParams) error {
	_, err := q.db.ExecContext(ctx, updateTermOccasion, arg.Name, arg.ID)
	return err
}
