services:
  echo:
    image: whlapinel/course-manager:local-dev
    command: ["./cmd/app/app"]
    build:
      context: .
      dockerfile: Dockerfile.echo.dev
    volumes:
      - ./cmd/app:/app/cmd/app
      - ./internal/data/users:/app/internal/data/users
      # - ./sites:/app/sites # old static sites directory
      - ./hugosites:/app/hugosites # new sites directory
      - ./internal/staticresources:/app/internal/staticresources
      - ./course_manager.db:/app/course_manager.db
