services:
  caddy:
    command:
      [
        "caddy",
        "run",
        "--config",
        "/etc/caddy/Caddyfile.prod",
        "--adapter",
        "caddyfile",
      ]
  echo:
    environment:
      - PRODUCTION=true
networks:
  app-network:
    driver: bridge
