FROM ubuntu:latest

# Set working directory
WORKDIR /app

# Install dependencies (if needed)
RUN apt-get update && apt-get install -y ca-certificates

# Install dependencies and Hugo
RUN apt-get update && \
    apt-get install -y ca-certificates curl && \
    curl -L -o hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.147.3/hugo_0.147.3_Linux-64bit.tar.gz && \
    tar -xzf hugo.tar.gz hugo && \
    mv hugo /usr/local/bin/hugo && \
    rm hugo.tar.gz

ARG USER_ID=1000
ARG GROUP_ID=1000

# Create group and user
RUN groupadd -g $GROUP_ID whlapinel && \
    useradd -u $USER_ID -g $GROUP_ID -m -s /bin/bash whlapinel

# Switch to the new user
USER whlapinel

# Mount the locally built binary at runtime
CMD ["./cmd/app/app"]
