version: "3"

tasks:
  export-secrets:
    desc: Export all secret files in a separate folder for publishing elsewhere
    cmds:
      - go run ./cmd/export_secret

  generate:
    desc: Generate stuff and things
    cmds:
      - go generate ./...

  sync-site:
    desc: Push generated site code to GitHub to make publicly available
    cmds:
      - cd python && git add .
      - cd python && git commit -m "auto-sync"
      - cd python && git push

  dev-run-full:
    desc: Generate then run
    deps:
      - generate
    cmds:
      - echo 'Starting Course Manager'
      - go run ./cmd/web_app

  dev-run:
    desc: Build and run without generate (for when we're not changing UI)
    cmds:
      - go run ./cmd/web_app

  tar-data:
    desc: Prepare database and files for sending to remote server
    cmds:
      - mkdir build
      - mkdir build/internal
      - mkdir build/internal/data
      - mkdir build/internal/data/database
      - cp -r ./internal/data/users ./build/internal/data
      - cp internal/data/database/course_manager.db ./build/internal/data/database/course_manager.db
      - tar -czf data.tar.gz -C ./build .

  tar-build:
    desc: Self-explanatory
    cmds:
      - mkdir build
      - mkdir build/cmd
      - mkdir build/cmd/web_app
      - mkdir build/internal
      - mkdir build/internal/data
      - mkdir build/internal/data/database
      - mkdir build/internal/data/database/migrations
      - go build -o ./build/cmd/web_app ./cmd/web_app
      - cp -r internal/data/database/migrations ./build/internal/data/database/migrations
      - tar -czf web_app.tar.gz -C ./build .
