version: "3"

tasks:
  hello:
    cmds:
      - echo 'Hello World from Task!'
    silent: true

  sync:
    cmds:
      - cd python && git add .
      - cd python && git commit -m "auto-sync"
      - cd python && git push
      - cd python && git switch main
      - cd python && git merge dev -m "auto"
      - cd python && git push
      - cd python && git switch dev

  run-manager:
    - echo 'Starting Course Manager'
    - go run ./cmd/fyne_app

  build:
    cmds:
      - echo 'running templ generate...'
      - templ generate
      - echo 'running tsc build...'
      - tsc --build
      - echo 'running npx tailwindcss...'
      - npx tailwindcss -i ./input.css -o ./python/docs/styles/styles.css
      - echo 'running go run...'
      - go run ./cmd/gen_site
