version: "3"
vars:
  DB_PATH: ./course_manager.db

tasks:
  generate:
    desc: generates all
    deps: [sqlc, templ, tailwind-app, tailwind-static, typescript]
  
  sqlc:
    cmds:
      - sqlc generate

  typescript:
    cmds:
      - npx tsc --build

  templ:
    desc: generates go template files for app
    cmds:
      - templ generate

  tailwind-static:
    desc: generates tailwindcss for app and static site resources
    cmds:
      - npx tailwindcss -i ./static-input.css -o ./internal/staticresources/static/styles/styles.css

  tailwind-app:
    cmds:
      - npx tailwindcss -i ./manager-input.css -o ./internal/assets/dist/styles.css

  export-secrets:
    desc: Export all secret files in a separate folder for publishing elsewhere
    cmds:
      - go run ./cmd/export_secret

  create-migration:*:
    vars:
      NAME: "{{index .MATCH 0}}"
      
    desc: For creating a new db migration
    cmds:
      - cd internal/infrastructure/sqlite/migrations/schema && goose sqlite3 {{.DB_PATH}} create {{.NAME}} go

  migrate:
    desc: Run migrations (intended only for running on development database, as this step is included via container in deployment script)
    cmds:
      - go run ./cmd/migrate -dir="internal/infrastructure/sqlite/migrations/schema" course_manager.db up 
      - sqlite3 course_manager.db ".schema" | sed 's/"//g' > "internal/infrastructure/sqlite/sqlc/schema.sql"


  # sync-site:
  #   desc: (For old GitHub pages site generator) push generated site code to GitHub to make publicly available
  #   cmds:
  #     - cd python && git add .
  #     - cd python && git commit -m "auto-sync"
  #     - cd python && git push

  run-dev:
    desc: Build and run without generate (for when we're not changing UI)
    deps:
      - generate
    cmds:
      - go build -o ./cmd/app ./cmd/app
      - docker compose -f compose.yaml -f compose.dev.yaml up --build --remove-orphans

  restart:
    desc: Stops, rebuilds and restarts the echo container only
    deps:
      - generate
    cmds:
      - templ generate
      - go build -o ./cmd/app/app ./cmd/app
      - docker compose restart echo

  run-prod:
    desc: To be run from production server
    cmds:
      - docker compose down
      - docker compose pull
      - docker compose run --rm migrate
      - docker compose -f compose.yaml -f compose.prod.yaml up --remove-orphans

  # copy-data:
  #   desc: Copy data to remote server
  #   cmds:
  #     - ./scripts/copy_data.sh
  #     - echo 'after ssh started, run task unpack-data'
  #     - ssh root@159.223.174.80

  unpack-data:
    desc: To be run on remote server. Runs script to unpack data
    cmds:
      - chmod +x ./scripts/unpack_data.sh
      - ./scripts/unpack_data.sh
  ssh:
    desc: ssh into server
    cmds:
      - ssh root@159.223.174.80

  deploy:
    desc: Build image, push to docker hub, copy scripts to remote server, ssh to server
    cmds:
      - docker compose build
      - docker compose push
      - ./scripts/copy_config.sh
      - echo 'after ssh started, run task run-prod'
      - ssh root@159.223.174.80

  backup:
    desc: Manual backup to remote repo on github. This is already scheduled for automatic daily backup with cron on the remote server.
    cmds:
      - ./scripts/backup.sh

  restore:
    desc: Restore from backup.
    cmds:
      - ./scripts/restore_backup.sh
