baseURL = '{{ .BaseURL }}'
languageCode = 'en-us'
title = '{{ .Title }}'
[module]
[[module.mounts]]
source = 'content'
target = 'content'
[[module.mounts]]
source = '/app/internal/staticresources/content'
target = 'content'
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
source = '{{ .UserDataPath }}'
target = 'assets'
[[module.mounts]]
source = 'static'
target = 'static'
[[module.mounts]]
source = '/app/internal/staticresources/static'
target = 'static'
[[module.mounts]]
source = 'layouts'
target = 'layouts'
[[module.mounts]]
source = '/app/internal/staticresources/layouts'
target = 'layouts'