baseURL = '{{ .BaseURL }}'
languageCode = 'en-us'
title = '{{ .Title }}'
[params]
subtitle = '{{.Subtitle}}'
username = '{{.Username}}'
[module]
[[module.mounts]]
source = 'content'
target = 'content'
[[module.mounts]]
source = '{{ .UserDataPath }}'
target = 'content'
[[module.mounts]]
source = '/app/internal/staticresources/content'
target = 'content'
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
source = '{{ .UserDataPath }}'
target = 'assets'
[[module.mounts]]
source = 'static'
target = 'static'
[[module.mounts]]
source = '/app/internal/staticresources/static'
target = 'static'
[[module.mounts]]
source = 'layouts'
target = 'layouts'
[[module.mounts]]
source = '/app/internal/staticresources/layouts'
target = 'layouts'
[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Units'
    pageRef = '/units'
    weight = 20
  [[menus.main]]
    name = 'Calendar'
    pageRef = '/calendar'
    weight = 30
  [[menus.main]]
    name = 'Course Files'
    pageRef = '/files'
    weight = 40
