// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: dates.sql

package database

import (
	"context"
)

const deleteDate = `-- name: DeleteDate :exec
DELETE FROM dates
WHERE date = ? AND term_id = ?
`

type DeleteDateParams struct {
	Date   string
	TermID int64
}

func (q *Queries) DeleteDate(ctx context.Context, arg DeleteDateParams) error {
	_, err := q.db.ExecContext(ctx, deleteDate, arg.Date, arg.TermID)
	return err
}

const getDate = `-- name: GetDate :one
SELECT id, term_id, date FROM dates WHERE date = ?
`

func (q *Queries) GetDate(ctx context.Context, date string) (Date, error) {
	row := q.db.QueryRowContext(ctx, getDate, date)
	var i Date
	err := row.Scan(&i.ID, &i.TermID, &i.Date)
	return i, err
}

const saveDate = `-- name: SaveDate :one
INSERT INTO dates (
  term_id, date
) VALUES (
  ?, ?
)
RETURNING id, term_id, date
`

type SaveDateParams struct {
	TermID int64
	Date   string
}

func (q *Queries) SaveDate(ctx context.Context, arg SaveDateParams) (Date, error) {
	row := q.db.QueryRowContext(ctx, saveDate, arg.TermID, arg.Date)
	var i Date
	err := row.Scan(&i.ID, &i.TermID, &i.Date)
	return i, err
}
