// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: occasions.sql

package database

import (
	"context"
)

const deleteOccasion = `-- name: DeleteOccasion :exec
DELETE FROM occasions WHERE id = ?
`

func (q *Queries) DeleteOccasion(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteOccasion, id)
	return err
}

const getOccasionByID = `-- name: GetOccasionByID :one
SELECT id, term_id, date, name FROM occasions WHERE id = ?
`

func (q *Queries) GetOccasionByID(ctx context.Context, id int64) (Occasion, error) {
	row := q.db.QueryRowContext(ctx, getOccasionByID, id)
	var i Occasion
	err := row.Scan(
		&i.ID,
		&i.TermID,
		&i.Date,
		&i.Name,
	)
	return i, err
}

const getTermOccasions = `-- name: GetTermOccasions :many
SELECT id, term_id, date, name FROM occasions WHERE term_id = ?
`

func (q *Queries) GetTermOccasions(ctx context.Context, termID int64) ([]Occasion, error) {
	rows, err := q.db.QueryContext(ctx, getTermOccasions, termID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Occasion
	for rows.Next() {
		var i Occasion
		if err := rows.Scan(
			&i.ID,
			&i.TermID,
			&i.Date,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveOccasion = `-- name: SaveOccasion :one
INSERT INTO occasions (
    term_id, date, name
) VALUES (
    ?, ?, ?
)
RETURNING id, term_id, date, name
`

type SaveOccasionParams struct {
	TermID int64
	Date   string
	Name   string
}

func (q *Queries) SaveOccasion(ctx context.Context, arg SaveOccasionParams) (Occasion, error) {
	row := q.db.QueryRowContext(ctx, saveOccasion, arg.TermID, arg.Date, arg.Name)
	var i Occasion
	err := row.Scan(
		&i.ID,
		&i.TermID,
		&i.Date,
		&i.Name,
	)
	return i, err
}

const updateOccasion = `-- name: UpdateOccasion :exec
UPDATE occasions SET name=? WHERE id=?
`

type UpdateOccasionParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateOccasion(ctx context.Context, arg UpdateOccasionParams) error {
	_, err := q.db.ExecContext(ctx, updateOccasion, arg.Name, arg.ID)
	return err
}
