// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: standard_sets.sql

package database

import (
	"context"
)

const getAllStandardSets = `-- name: GetAllStandardSets :many
SELECT id, course_name FROM standard_sets
`

func (q *Queries) GetAllStandardSets(ctx context.Context) ([]StandardSet, error) {
	rows, err := q.db.QueryContext(ctx, getAllStandardSets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StandardSet
	for rows.Next() {
		var i StandardSet
		if err := rows.Scan(&i.ID, &i.CourseName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStdSetByCourseName = `-- name: GetStdSetByCourseName :one
SELECT id, course_name FROM standard_sets WHERE course_name = ?
`

func (q *Queries) GetStdSetByCourseName(ctx context.Context, courseName string) (StandardSet, error) {
	row := q.db.QueryRowContext(ctx, getStdSetByCourseName, courseName)
	var i StandardSet
	err := row.Scan(&i.ID, &i.CourseName)
	return i, err
}

const getStdSetByID = `-- name: GetStdSetByID :one
SELECT id, course_name FROM standard_sets WHERE id = ?
`

func (q *Queries) GetStdSetByID(ctx context.Context, id int64) (StandardSet, error) {
	row := q.db.QueryRowContext(ctx, getStdSetByID, id)
	var i StandardSet
	err := row.Scan(&i.ID, &i.CourseName)
	return i, err
}

const saveStandardSet = `-- name: SaveStandardSet :one
INSERT INTO standard_sets (
    course_name
) VALUES (
    ?
) RETURNING id, course_name
`

func (q *Queries) SaveStandardSet(ctx context.Context, courseName string) (StandardSet, error) {
	row := q.db.QueryRowContext(ctx, saveStandardSet, courseName)
	var i StandardSet
	err := row.Scan(&i.ID, &i.CourseName)
	return i, err
}
