// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: units.sql

package database

import (
	"context"
	"database/sql"
)

const deleteUnit = `-- name: DeleteUnit :one
DELETE FROM units WHERE id = ?
RETURNING id, course_id, number, sequence, name, description
`

func (q *Queries) DeleteUnit(ctx context.Context, id int64) (Unit, error) {
	row := q.db.QueryRowContext(ctx, deleteUnit, id)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Number,
		&i.Sequence,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const getUnit = `-- name: GetUnit :one
SELECT id, course_id, number, sequence, name, description FROM units u WHERE u.id = ?
`

func (q *Queries) GetUnit(ctx context.Context, id int64) (Unit, error) {
	row := q.db.QueryRowContext(ctx, getUnit, id)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Number,
		&i.Sequence,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const getUnits = `-- name: GetUnits :many
SELECT
  u.id,
  u.course_id,
  u.number,
  u.sequence,
  u.name,
  u.description
FROM
  units u
WHERE
  u.course_id = ?
ORDER BY
  u.sequence
`

func (q *Queries) GetUnits(ctx context.Context, courseID int64) ([]Unit, error) {
	rows, err := q.db.QueryContext(ctx, getUnits, courseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Unit
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.CourseID,
			&i.Number,
			&i.Sequence,
			&i.Name,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveUnit = `-- name: SaveUnit :one
INSERT INTO units (
  number, sequence, name, description, course_id
) VALUES (
  ?, ?, ?, ?, ?
)
RETURNING id, course_id, number, sequence, name, description
`

type SaveUnitParams struct {
	Number      int64
	Sequence    int64
	Name        string
	Description sql.NullString
	CourseID    int64
}

func (q *Queries) SaveUnit(ctx context.Context, arg SaveUnitParams) (Unit, error) {
	row := q.db.QueryRowContext(ctx, saveUnit,
		arg.Number,
		arg.Sequence,
		arg.Name,
		arg.Description,
		arg.CourseID,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.CourseID,
		&i.Number,
		&i.Sequence,
		&i.Name,
		&i.Description,
	)
	return i, err
}

const updateUnit = `-- name: UpdateUnit :exec
UPDATE units
SET number = ?, sequence = ?, name = ?, description = ?
WHERE id = ?
`

type UpdateUnitParams struct {
	Number      int64
	Sequence    int64
	Name        string
	Description sql.NullString
	ID          int64
}

func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) error {
	_, err := q.db.ExecContext(ctx, updateUnit,
		arg.Number,
		arg.Sequence,
		arg.Name,
		arg.Description,
		arg.ID,
	)
	return err
}
