baseURL = 'https://101602110272674353046.localhost'
languageCode = 'en-us'
title = 'wlapinel'
[module]
[[module.mounts]]
source = 'content'
target = 'content'
[[module.mounts]]
source = '/app/internal/staticresources/content'
target = 'content'
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
source = '/app/internal/data/users/user_101602110272674353046'
target = 'assets'
[[module.mounts]]
source = 'static'
target = 'static'
[[module.mounts]]
source = '/app/internal/staticresources/static'
target = 'static'
[[module.mounts]]
source = 'layouts'
target = 'layouts'
[[module.mounts]]
source = '/app/internal/staticresources/layouts'
target = 'layouts'