// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: files.sql

package database

import (
	"context"
	"database/sql"
)

const saveFile = `-- name: SaveFile :one
INSERT INTO files (
 name, description, file_name, modified
) VALUES (
    ?, ?, ?, ?
)
RETURNING id, name, description, file_name, modified
`

type SaveFileParams struct {
	Name        string
	Description sql.NullString
	FileName    string
	Modified    string
}

func (q *Queries) SaveFile(ctx context.Context, arg SaveFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, saveFile,
		arg.Name,
		arg.Description,
		arg.FileName,
		arg.Modified,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.FileName,
		&i.Modified,
	)
	return i, err
}
