// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: terms.sql

package database

import (
	"context"
)

const deleteNonInstructDays = `-- name: DeleteNonInstructDays :one
DELETE FROM non_instruct_days WHERE id = ?
RETURNING id, term_id, date
`

func (q *Queries) DeleteNonInstructDays(ctx context.Context, id int64) (NonInstructDay, error) {
	row := q.db.QueryRowContext(ctx, deleteNonInstructDays, id)
	var i NonInstructDay
	err := row.Scan(&i.ID, &i.TermID, &i.Date)
	return i, err
}

const deleteTerm = `-- name: DeleteTerm :one
DELETE FROM terms WHERE id = ?
RETURNING id, name, start, "end"
`

func (q *Queries) DeleteTerm(ctx context.Context, id int64) (Term, error) {
	row := q.db.QueryRowContext(ctx, deleteTerm, id)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Start,
		&i.End,
	)
	return i, err
}

const getTerm = `-- name: GetTerm :one
SELECT
  t.id,
  t.name
FROM
  terms t
JOIN
  dates d ON d.term_id = t.id
WHERE
  d.date = ?
`

type GetTermRow struct {
	ID   int64
	Name string
}

func (q *Queries) GetTerm(ctx context.Context, date string) (GetTermRow, error) {
	row := q.db.QueryRowContext(ctx, getTerm, date)
	var i GetTermRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const saveTerm = `-- name: SaveTerm :one
INSERT INTO terms (
  name, start, end
) VALUES (
  ?, ?, ?
)
RETURNING id, name, start, "end"
`

type SaveTermParams struct {
	Name  string
	Start string
	End   string
}

func (q *Queries) SaveTerm(ctx context.Context, arg SaveTermParams) (Term, error) {
	row := q.db.QueryRowContext(ctx, saveTerm, arg.Name, arg.Start, arg.End)
	var i Term
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Start,
		&i.End,
	)
	return i, err
}
